"""empty message

Revision ID: 152bb1509596
Revises: 774e5b37d9ef
Create Date: 2023-10-20 12:29:05.993376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152bb1509596'
down_revision = '774e5b37d9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_admin', schema=None) as batch_op:
        batch_op.drop_constraint('business_admin_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('business_admin_business_id_fkey', 'business', ['business_id'], ['id'])

    # ### end Alembic commands ###
