"""empty message

Revision ID: 335725c93c94
Revises: 28f08f56d09e
Create Date: 2023-10-21 10:59:21.269588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335725c93c94'
down_revision = '28f08f56d09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
