"""empty message

Revision ID: 506ef623d882
Revises: 0007c558adf0
Create Date: 2023-10-21 10:56:31.917183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506ef623d882'
down_revision = '0007c558adf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint('staff_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('staff_business_id_fkey', 'business', ['business_id'], ['id'])

    # ### end Alembic commands ###
