"""empty message

Revision ID: 774e5b37d9ef
Revises: a7e917361d51
Create Date: 2023-10-20 12:28:35.600054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774e5b37d9ef'
down_revision = 'a7e917361d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('roles_business_id_fkey', 'business', ['business_id'], ['id'])

    # ### end Alembic commands ###
