"""empty message

Revision ID: a6b8a945908f
Revises: f637f4c72391
Create Date: 2023-10-21 10:19:54.734511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6b8a945908f'
down_revision = 'f637f4c72391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name='property_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='property_pkey')
    )
    # ### end Alembic commands ###
