"""empty message

Revision ID: f4446f6ff271
Revises: 9bc95fe3b55a
Create Date: 2023-10-28 11:53:24.753139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4446f6ff271'
down_revision = '9bc95fe3b55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_admin', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
